spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_android?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  enable-csrf: false
  enable-cors: false
  servlet:
    session:
      cookie:
        http-only: true
        secure: false  # chỉ bật true nếu dùng HTTPS
        max-age: 1800
